# Site settings
title: Gaurav Mishra
twitter_username: Gaurav20100G
name: Gaurav Mishra

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://skill-explorer.blogspot.com/
 - title: GitHub
   url: https://github.com/ItzGaurav
 - title: StackOverflow
   url: https://stackoverflow.com/users/9121809/gaurav
 - title: LinkedIn
   url: https://www.linkedin.com/in/gaurav20100

#Any buzzword skills you want to include
skills:
 - C#
 - ASP.NET
 - ASP.NET MVC
 - WebApi
 - JavaScript
 - JQuery
 - Angular
 - NodeJS
 - MongoDB
 - SQL Server
 - SOLID Principles
 - Azure
 - Azure IoT hub
 - Azure Event Hub
 - Azure IoT Edge
 - Device Twins
 - Azure DPS
 - Blob Data Storage
 - CosmosDB

#Work experience is required
roles:
 - title: Senior Software Engineer
   start: March 2017
   end: Ongoing
   employer: Marlabs Innovatioon, Bangalore
   description: I have involved in end-to-end development of software applications and IoT application from requirement analysis to system study, designing, coding, unit testing, debugging, documentation and implementation.
 - title: Software Engineer
   start: November 2014
   end: March 2017
   employer: CRMnext (Acidaes Solution Pvt. Ltd.)
   description: I have worked on multiple module of CRM Product and got good knowledge of CRM Domain with MVC, JQuery, SqlServer experience.
 - title: Junior Engineer
   start: September 2013
   end: November 2014
   employer: Multivirt India Pvt. Ltd.
   description: A range of functional and technical roles, primarily working on C# and asp.net.

#Education is required
education:
 - level: Bachelor of Technology (B.Tech.)
   date: May 2013
   Branch: Information Technology (IT)
   University: Uttar Pradesh Technical University

#This section is optional (as is the image link below)
RecentProjects:
   profileurl: http://gaurav20100.wixsite.com/gaurav/projects
   courses:
#This section is optional (as is the image link below)
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014


#List of interesting Github repo/projects to include - optional
github:
 - ItzGaurav/Concepts
 - ItzGaurav/Angular-2
 - ItzGaurav/Angular2-ReactiveForm
 - ItzGaurav/Ionic-fireBase
 - ItzGaurav/Ionic-CameraAccess
 - ItzGaurav/ionic-GoogleMap


#Mobile apps section is optional
apps:
 - name: News Channel
   platform: Android
   url: Not on playStore
   description: A basic early Android app (open sourced)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>IOT</strong>: I am experienced in IoT application development  like Smart Fan, Smart Socket, Smart AC. I have primarily used Azure IoT hub, Event Hub, IoT Edge, Device Twins, Azure DPS, Azure Function, Data Storage for IOT. <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running MEAN production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3. <br/><br/>
   <strong> MEAN</strong>: My current role uses Angular, NodeJs and MongoDB as the primary language and have been building applications in MEAN for the last year.
   <strong>ASP.NET</strong>: I am experienced in a variety of .net Projects. I have good knowledge of asp.net MVC. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the  MVC framework. I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git,TFS, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects that I have undertaken in my free time, including Hybrid Mobile app development and learning new technologies. <br/><br/>
