# Site settings
title: Gaurav Mishra
twitter_username: Gaurav20100G
name: Gaurav Mishra

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://skill-explorer.blogspot.com/
 - title: GitHub
   url: https://github.com/ItzGaurav
 - title: StackOverflow
   url: https://stackoverflow.com/users/9121809/gaurav
 - title: LinkedIn
   url: https://www.linkedin.com/in/gaurav20100

#Any buzzword skills you want to include
skills:
 - C#
 - ASP.NET
 - ASP.NET MVC
 - WebApi
 - Angular
 - NodeJS
 - SQL
 - REST
 - Tech Architecture

#Work experience is required
roles:
 - title: Senior Software Engineer
   start: March 2017
   end: Ongoing
   employer: Marlabs Innovatioon, Bangalore
   description: I am working on Knowledge Domain and as a MEAN stack Developer (Angular,Node, Mongo).
 - title: Software Engineer
   start: November 2014
   end: March 2017
   employer: CRMnext (Acidaes Solution Pvt. Ltd.)
   description: I have worked on multiple object of CRM Product and got good knowledge of CRM Domain with MVC, JQuery, SqlServer experience.
 - title: Junior Engineer
   start: September 2013
   end: November 2014
   employer: Multivirt India Pvt. Ltd.
   description: A range of functional and technical roles, primarily working on C# and asp.net.

#Education is required
education:
 - level: Bachelor of Technology (B.Tech.)
   date: May 2013
   Branch: Information Technology (IT)
   University: Uttar Pradesh Technical University

#This section is optional (as is the image link below)
RecentProjects:
   profileurl: http://gaurav20100.wixsite.com/gaurav/projects
   courses:
    •	Project #1:  Survey                                                                                   July 2016 – Till date
Client: SBI, HDFC, ICICI, Axis Bank etc.    
Tool Used: C#, ASP.NET, MVC, SQL Server, ADO.NET and JQuery, AngularJs
Description: If you are providing some services, you need to keep track of those services by collecting inputs from customers. These inputs may be via Email, Phone call, Facebook. This enables an organisation to expand its customer base and retain them. Survey is all about customer experience.
  Responsibilities:
•	Managing and delivering the project being a module lead.
•	Involved in design and development
•	Writing Unit Tests

•	Project #2/3:  Outlook 365 Integration /   Email Syndication                May 2015 – June 2016                                          
Domain: Customer Relationship Management
Client: SBI, HDFC, ICICI, Axis Bank etc.    
Tool Used: C#, ASP.NET, MVC, SQL Server, ADO.NET and JQuery.
Description: In Outlook Integration we brought whole CRM experience to single window. While reading an Email one can search/create possible Leads/Contacts by just clicking single button.   
Email syndication is about connecting the Email Accounts with CRM. It converts email in to Lead/Case.
Email syndication is useful for customer support executives. An organisation may get thousands of emails every day regarding their Product’s Complaint/Feedback. It is nearly impossible to track each and every email.

  Responsibilities:
•	Managing the project being a second module lead.
•	Completing modules and requirements, solving complex problems and guiding new developers about the module.


•	Project #4:  CRMnext                                                                 January 2015 – Till date
Domain: Customer Relationship Management
Client: SBI, HDFC, ICICI, Axis Bank etc.    
Tool Used: C#, ASP.NET, MVC, SQL Server, ADO.NET and JQuery.
Description: CRMnext has established technology and practice leadership in multiple industry verticals to help its customers boost profitability by improving all customer related processes. It works closely with its customers, leveraging their extensive cross-domain expertise to enhance business efficiency by improving processes and practices. 
  Responsibilities:
•	Responsible for Coding ,Customer bug fixing and Unit testing.
•	Completing modules and requirements which have been assigned to me.


#List of interesting Github repo/projects to include - optional
github:
 - ItzGaurav/CodeSharing   // 50+ conceptual Programs
 - ItzGaurav/Angular-2     // Angular Project with CRUD operation
 - ItzGaurav/ionic-map     // Mobile App using Google Map Api
 - ItzGaurav/Ionic-fireBase  // Mobile App- saving data at fireBase(Google databse)



#Mobile apps section is optional
apps:
 - name: News Channel
   platform: Android
   url: Not on playStore
   description: A basic early Android app (open sourced)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>ASP.NET</strong>: I am experienced in a variety of .net Projects. I have good knowledge of asp.net MVC. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the  MVC framework. I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git,TFS, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects that I have undertaken in my free time, including Hybrid Mobile app development and learning new technologies. <br/><br/>
